{% set name = "pyiron_potentialfit" %}
{% set version = "0.3.11" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyiron_potentialfit-{{ version }}.tar.gz
  sha256: fdce5e49bf639c1bce94541fac7548bc305db546d001c185c713784c5a77496e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - pyparsing >=3.1.2,<3.2
    - pyiron_contrib >=0.1.18
    - pyiron_snippets >=0.1.1,<=0.1.4
    - pyxtal >=0.6.0,<1.1
    - dill >=0.3.0
    - seaborn >=0.13.0,<0.14
    - runnerase >=0.3.3
    - python >={{ python_min }}
    - ase >=3.25.0
    - pyiron_atomistics >=0.7.8
    - matplotlib-base >=3.8.4,<4
    - numpy >=1.26.4
    - pyiron_base >=0.13.0
    - scipy >=1.15.2

test:
  imports:
    - pyiron_potentialfit
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyiron/pyiron_potentialfit
  summary: Fitting machine learning interatomic potentials with pyiron.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - niklassiemer
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
