{% set name = "pyiron_potentialfit" %}
{% set version = "0.3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyiron_potentialfit-{{ version }}.tar.gz
  sha256: 44c384a5f924c9b2586da0b67d0a53646a512773b6668e3a1ba1d4ac77608463

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - pyparsing >=3.1.2,<3.2
    - pyiron_contrib >=0.1.18
    - pyiron_snippets >=0.1.1,<=0.1.4
    - pyxtal >=0.6.0,<1.1
    - dill >=0.3.0
    - seaborn >=0.13.0,<0.14
    - runnerase >=0.3.3
    - python >=3.8
    - ase >=3.23.0
    - pyiron_atomistics >=0.6.18
    - matplotlib-base >=3.8.4,<4
    - numpy >=1.26.4
    - pyiron_base >=0.10.9
    - scipy >=1.14.0

test:
  imports:
    - pyiron_potentialfit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/pyiron_potentialfit
  summary: Fitting machine learning interatomic potentials with pyiron.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - niklassiemer
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
