{% set name = "pyiron_potentialfit" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyiron_potentialfit-{{ version }}.tar.gz
  sha256: 8b1e80c9087afc2295ddd233384dc41e0e60e1ed7d15351b39bf94f7032fb81c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - pyiron_contrib >=0.1.16
    - pyiron_snippets >=0.1.1,<=0.1.3
    - pyxtal >=0.6.0,<0.7
    - dill >=0.3.0
    - seaborn >=0.13.0,<0.14
    - runnerase >=0.3.3
    - python >=3.8
    - ase >=3.23.0
    - pyiron_atomistics >=0.6.9
    - matplotlib-base >=3.8.4
    - numpy >=1.26.4
    - pyiron_base >=0.9.10
    - scipy >=1.14.0

test:
  imports:
    - pyiron_potentialfit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/pyiron_potentialfit
  summary: Fitting machine learning interatomic potentials with pyiron.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - niklassiemer
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
