{% set name = "pyiron_potentialfit" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyiron_potentialfit-{{ version }}.tar.gz
  sha256: d4cc958345bdffa06f8607b6ca907eda381b915ec7ffa341fd38e9e0db90608f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - pyxtal >=0.6.0,<0.7
    - dill >=0.3.0
    - seaborn >=0.13.0,<0.14
    - runnerase >=0.3.3
    - python >=3.8
    - ase >=3.22.1
    - pyiron_atomistics >=0.5.2
    - matplotlib-base >=3.8.4
    - numpy >=1.26.4
    - pyiron_base >=0.8.2
    - scipy >=1.13.0

test:
  imports:
    - pyiron_potentialfit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/pyiron_potentialfit
  summary: Fitting machine learning interatomic potentials with pyiron.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
